#!/bin/bash

#mpirun -n 6 python para_combine_1d.py  ~/mnt2/sbs-1d/1e14/MS/FLD/e1 /Volumes/Lacie-5TB/work/LLNL-2018/1d-tests/1e14/t9/e1.h5
#mpirun -n 6 python para_combine_1d.py  ~/mnt2/sbs-1d/1e14/MS/FLD/b3 /Volumes/Lacie-5TB/work/LLNL-2018/1d-tests/1e14/t9/b3.h5
#mpirun -n 6 python para_combine_1d.py  ~/mnt2/sbs-1d/1e14/MS/FLD/e1 /Volumes/Lacie-5TB/work/LLNL-2018/1d-tests/1e14/t9/e1.h5

#mpirun -n 6 python para_e2_decomp.py -n 0.38 ~/mnt2/sbs-1d/1e14/MS/ /Volumes/Lacie-5TB/work/LLNL-2018/1d-tests/1e14/t9/

in_folder="/Users/franktsung/mnt2/sbs-1d/2e14/MS-t20/"
out_folder="/Volumes/Lacie-5TB/work/LLNL-2018/1d-tests/2e14/t20/"

mpirun -n 6 python para_combine_1d.py $in_folder"/DENSITY/species_2/charge" $out_folder"/rhoi.h5"
mpirun -n 6 python para_combine_1d.py $in_folder"/FLD/e1" $out_folder"/e1.h5"
mpirun -n 6 python para_combine_1d.py $in_folder"/FLD/e2" $out_folder"/e2.h5"
mpirun -n 6 python para_combine_1d.py $in_folder"/FLD/b3" $out_folder"/b3.h5"
mpirun -n 6 python para_poynt.py $in_folder $out_folder"/s1.h5"

mpirun -n 6 python para_e2_decomp.py -n 0.38 $in_folder $out_folder

in_folder="/Users/franktsung/mnt2/sbs-1d/2e14/MS/"
out_folder="/Volumes/Lacie-5TB/work/LLNL-2018/1d-tests/2e14/t9/"

mpirun -n 6 python para_combine_1d.py $in_folder"/DENSITY/species_2/charge" $out_folder"/rhoi.h5"
mpirun -n 6 python para_combine_1d.py $in_folder"/FLD/e1" $out_folder"/e1.h5"
mpirun -n 6 python para_combine_1d.py $in_folder"/FLD/e2" $out_folder"/e2.h5"
mpirun -n 6 python para_combine_1d.py $in_folder"/FLD/b3" $out_folder"/b3.h5"
mpirun -n 6 python para_poynt.py $in_folder $out_folder"/s1.h5"

mpirun -n 6 python para_e2_decomp.py -n 0.38 $in_folder $out_folder


in_folder="/Users/franktsung/mnt2/sbs-1d/3e14/MS-t20/"
out_folder="/Volumes/Lacie-5TB/work/LLNL-2018/1d-tests/3e14/t20/"

mpirun -n 6 python para_combine_1d.py $in_folder"/DENSITY/species_2/charge" $out_folder"/rhoi.h5"
mpirun -n 6 python para_combine_1d.py $in_folder"/FLD/e1" $out_folder"/e1.h5"
mpirun -n 6 python para_combine_1d.py $in_folder"/FLD/e2" $out_folder"/e2.h5"
mpirun -n 6 python para_combine_1d.py $in_folder"/FLD/b3" $out_folder"/b3.h5"
mpirun -n 6 python para_poynt.py $in_folder $out_folder"/s1.h5"

mpirun -n 6 python para_e2_decomp.py -n 0.38 $in_folder $out_folder

in_folder="/Users/franktsung/mnt2/sbs-1d/3e14/MS/"
out_folder="/Volumes/Lacie-5TB/work/LLNL-2018/1d-tests/3e14/t9/"

mpirun -n 6 python para_combine_1d.py $in_folder"/DENSITY/species_2/charge" $out_folder"/rhoi.h5"
mpirun -n 6 python para_combine_1d.py $in_folder"/FLD/e1" $out_folder"/e1.h5"
mpirun -n 6 python para_combine_1d.py $in_folder"/FLD/e2" $out_folder"/e2.h5"
mpirun -n 6 python para_combine_1d.py $in_folder"/FLD/b3" $out_folder"/b3.h5"
mpirun -n 6 python para_poynt.py $in_folder $out_folder"/s1.h5"

mpirun -n 6 python para_e2_decomp.py -n 0.38 $in_folder $out_folder


in_folder="/Users/franktsung/mnt2/sbs-1d/4e14/MS-t20/"
out_folder="/Volumes/Lacie-5TB/work/LLNL-2018/1d-tests/4e14/t20/"

mpirun -n 6 python para_combine_1d.py $in_folder"/DENSITY/species_2/charge" $out_folder"/rhoi.h5"
mpirun -n 6 python para_combine_1d.py $in_folder"/FLD/e1" $out_folder"/e1.h5"
mpirun -n 6 python para_combine_1d.py $in_folder"/FLD/e2" $out_folder"/e2.h5"
mpirun -n 6 python para_combine_1d.py $in_folder"/FLD/b3" $out_folder"/b3.h5"
mpirun -n 6 python para_poynt.py $in_folder $out_folder"/s1.h5"

mpirun -n 6 python para_e2_decomp.py -n 0.38 $in_folder $out_folder

in_folder="/Users/franktsung/mnt2/sbs-1d/4e14/MS/"
out_folder="/Volumes/Lacie-5TB/work/LLNL-2018/1d-tests/4e14/t9/"

mpirun -n 6 python para_combine_1d.py $in_folder"/DENSITY/species_2/charge" $out_folder"/rhoi.h5"
mpirun -n 6 python para_combine_1d.py $in_folder"/FLD/e1" $out_folder"/e1.h5"
mpirun -n 6 python para_combine_1d.py $in_folder"/FLD/e2" $out_folder"/e2.h5"
mpirun -n 6 python para_combine_1d.py $in_folder"/FLD/b3" $out_folder"/b3.h5"
mpirun -n 6 python para_poynt.py $in_folder $out_folder"/s1.h5"

mpirun -n 6 python para_e2_decomp.py -n 0.38 $in_folder $out_folder

in_folder="/Users/franktsung/mnt2/sbs-1d/1e15/MS-t20/"
out_folder="/Volumes/Lacie-5TB/work/LLNL-2018/1d-tests/1e15/t20/"

mpirun -n 6 python para_combine_1d.py $in_folder"/DENSITY/species_2/charge" $out_folder"/rhoi.h5"
mpirun -n 6 python para_combine_1d.py $in_folder"/FLD/e1" $out_folder"/e1.h5"
mpirun -n 6 python para_combine_1d.py $in_folder"/FLD/e2" $out_folder"/e2.h5"
mpirun -n 6 python para_combine_1d.py $in_folder"/FLD/b3" $out_folder"/b3.h5"
mpirun -n 6 python para_poynt.py $in_folder $out_folder"/s1.h5"

mpirun -n 6 python para_e2_decomp.py -n 0.38 $in_folder $out_folder

in_folder="/Users/franktsung/mnt2/sbs-1d/1e15/MS/"
out_folder="/Volumes/Lacie-5TB/work/LLNL-2018/1d-tests/1e15/t9/"

mpirun -n 6 python para_combine_1d.py $in_folder"/DENSITY/species_2/charge" $out_folder"/rhoi.h5"
mpirun -n 6 python para_combine_1d.py $in_folder"/FLD/e1" $out_folder"/e1.h5"
mpirun -n 6 python para_combine_1d.py $in_folder"/FLD/e2" $out_folder"/e2.h5"
mpirun -n 6 python para_combine_1d.py $in_folder"/FLD/b3" $out_folder"/b3.h5"
mpirun -n 6 python para_poynt.py $in_folder $out_folder"/s1.h5"

mpirun -n 6 python para_e2_decomp.py -n 0.38 $in_folder $out_folder
